import z from "zod";
import { itemSchema } from "./list";

export const trackSchema = z.object({
  title: z.string().min(1),
  id: z.string().min(1),
  authorName: z.string().min(1).default("Auto-generated by YouTube"),
  authorId: z.string().optional(),
  thumbnails: z.array(
    z.object({
      url: z.string().min(1),
      width: z.number().min(1),
      height: z.number().min(1),
    })
  ),
  duration: z.number().min(1),
  url: z.string().optional(),
});

export type Track = z.infer<typeof trackSchema>;

export const trackListSchema = z.array(trackSchema);

export type TrackList = z.infer<typeof trackListSchema>;

export const trackDetailsSchema = trackSchema.extend({
  viewCount: z.number(),
  likes: z.number(),
  relatedVideos: z.array(itemSchema),
});

export type TrackDetails = z.infer<typeof trackDetailsSchema>;

export const trackListDetailsSchema = z.object({
  id: z.string().min(1),
  title: z.string().min(1),
  authorName: z.string().min(1),
  authorId: z.string().optional(),
  thumbnails: z.array(
    z.object({
      url: z.string().min(1),
      width: z.number().min(1),
      height: z.number().min(1),
    })
  ),
  items: trackListSchema,
});

export type TrackListDetails = z.infer<typeof trackListDetailsSchema>;
